// GENERATED by tools/generate_protocol_constants.py from upstream headers.
// Do not edit. Re-generate with:
//     python tools/generate_protocol_constants.py
//
// Upstream sources: gframe/ocgapi_constants.h, gframe/common.h
#ifndef EDOPRO_NEXT_CLIENT_PROTOCOL_CONSTANTS_H
#define EDOPRO_NEXT_CLIENT_PROTOCOL_CONSTANTS_H

#include <cstdint>
#include <string_view>

namespace edopro_next::client::protocol {

// --- duel messages ---
inline constexpr std::uint8_t MSG_RETRY                = 0x1;
inline constexpr std::uint8_t MSG_HINT                 = 0x2;
inline constexpr std::uint8_t MSG_WAITING              = 0x3;
inline constexpr std::uint8_t MSG_START                = 0x4;
inline constexpr std::uint8_t MSG_WIN                  = 0x5;
inline constexpr std::uint8_t MSG_UPDATE_DATA          = 0x6;
inline constexpr std::uint8_t MSG_UPDATE_CARD          = 0x7;
inline constexpr std::uint8_t MSG_REQUEST_DECK         = 0x8;
inline constexpr std::uint8_t MSG_SELECT_BATTLECMD     = 0xa;
inline constexpr std::uint8_t MSG_SELECT_IDLECMD       = 0xb;
inline constexpr std::uint8_t MSG_SELECT_EFFECTYN      = 0xc;
inline constexpr std::uint8_t MSG_SELECT_YESNO         = 0xd;
inline constexpr std::uint8_t MSG_SELECT_OPTION        = 0xe;
inline constexpr std::uint8_t MSG_SELECT_CARD          = 0xf;
inline constexpr std::uint8_t MSG_SELECT_CHAIN         = 0x10;
inline constexpr std::uint8_t MSG_SELECT_PLACE         = 0x12;
inline constexpr std::uint8_t MSG_SELECT_POSITION      = 0x13;
inline constexpr std::uint8_t MSG_SELECT_TRIBUTE       = 0x14;
inline constexpr std::uint8_t MSG_SORT_CHAIN           = 0x15;
inline constexpr std::uint8_t MSG_SELECT_COUNTER       = 0x16;
inline constexpr std::uint8_t MSG_SELECT_SUM           = 0x17;
inline constexpr std::uint8_t MSG_SELECT_DISFIELD      = 0x18;
inline constexpr std::uint8_t MSG_SORT_CARD            = 0x19;
inline constexpr std::uint8_t MSG_SELECT_UNSELECT_CARD = 0x1a;
inline constexpr std::uint8_t MSG_CONFIRM_DECKTOP      = 0x1e;
inline constexpr std::uint8_t MSG_CONFIRM_CARDS        = 0x1f;
inline constexpr std::uint8_t MSG_SHUFFLE_DECK         = 0x20;
inline constexpr std::uint8_t MSG_SHUFFLE_HAND         = 0x21;
inline constexpr std::uint8_t MSG_REFRESH_DECK         = 0x22;
inline constexpr std::uint8_t MSG_SWAP_GRAVE_DECK      = 0x23;
inline constexpr std::uint8_t MSG_SHUFFLE_SET_CARD     = 0x24;
inline constexpr std::uint8_t MSG_REVERSE_DECK         = 0x25;
inline constexpr std::uint8_t MSG_DECK_TOP             = 0x26;
inline constexpr std::uint8_t MSG_SHUFFLE_EXTRA        = 0x27;
inline constexpr std::uint8_t MSG_NEW_TURN             = 0x28;
inline constexpr std::uint8_t MSG_NEW_PHASE            = 0x29;
inline constexpr std::uint8_t MSG_CONFIRM_EXTRATOP     = 0x2a;
inline constexpr std::uint8_t MSG_MOVE                 = 0x32;
inline constexpr std::uint8_t MSG_POS_CHANGE           = 0x35;
inline constexpr std::uint8_t MSG_SET                  = 0x36;
inline constexpr std::uint8_t MSG_SWAP                 = 0x37;
inline constexpr std::uint8_t MSG_FIELD_DISABLED       = 0x38;
inline constexpr std::uint8_t MSG_SUMMONING            = 0x3c;
inline constexpr std::uint8_t MSG_SUMMONED             = 0x3d;
inline constexpr std::uint8_t MSG_SPSUMMONING          = 0x3e;
inline constexpr std::uint8_t MSG_SPSUMMONED           = 0x3f;
inline constexpr std::uint8_t MSG_FLIPSUMMONING        = 0x40;
inline constexpr std::uint8_t MSG_FLIPSUMMONED         = 0x41;
inline constexpr std::uint8_t MSG_CHAINING             = 0x46;
inline constexpr std::uint8_t MSG_CHAINED              = 0x47;
inline constexpr std::uint8_t MSG_CHAIN_SOLVING        = 0x48;
inline constexpr std::uint8_t MSG_CHAIN_SOLVED         = 0x49;
inline constexpr std::uint8_t MSG_CHAIN_END            = 0x4a;
inline constexpr std::uint8_t MSG_CHAIN_NEGATED        = 0x4b;
inline constexpr std::uint8_t MSG_CHAIN_DISABLED       = 0x4c;
inline constexpr std::uint8_t MSG_CARD_SELECTED        = 0x50;
inline constexpr std::uint8_t MSG_RANDOM_SELECTED      = 0x51;
inline constexpr std::uint8_t MSG_BECOME_TARGET        = 0x53;
inline constexpr std::uint8_t MSG_DRAW                 = 0x5a;
inline constexpr std::uint8_t MSG_DAMAGE               = 0x5b;
inline constexpr std::uint8_t MSG_RECOVER              = 0x5c;
inline constexpr std::uint8_t MSG_EQUIP                = 0x5d;
inline constexpr std::uint8_t MSG_LPUPDATE             = 0x5e;
inline constexpr std::uint8_t MSG_UNEQUIP              = 0x5f;
inline constexpr std::uint8_t MSG_CARD_TARGET          = 0x60;
inline constexpr std::uint8_t MSG_CANCEL_TARGET        = 0x61;
inline constexpr std::uint8_t MSG_PAY_LPCOST           = 0x64;
inline constexpr std::uint8_t MSG_ADD_COUNTER          = 0x65;
inline constexpr std::uint8_t MSG_REMOVE_COUNTER       = 0x66;
inline constexpr std::uint8_t MSG_ATTACK               = 0x6e;
inline constexpr std::uint8_t MSG_BATTLE               = 0x6f;
inline constexpr std::uint8_t MSG_ATTACK_DISABLED      = 0x70;
inline constexpr std::uint8_t MSG_DAMAGE_STEP_START    = 0x71;
inline constexpr std::uint8_t MSG_DAMAGE_STEP_END      = 0x72;
inline constexpr std::uint8_t MSG_MISSED_EFFECT        = 0x78;
inline constexpr std::uint8_t MSG_BE_CHAIN_TARGET      = 0x79;
inline constexpr std::uint8_t MSG_CREATE_RELATION      = 0x7a;
inline constexpr std::uint8_t MSG_RELEASE_RELATION     = 0x7b;
inline constexpr std::uint8_t MSG_TOSS_COIN            = 0x82;
inline constexpr std::uint8_t MSG_TOSS_DICE            = 0x83;
inline constexpr std::uint8_t MSG_ROCK_PAPER_SCISSORS  = 0x84;
inline constexpr std::uint8_t MSG_HAND_RES             = 0x85;
inline constexpr std::uint8_t MSG_ANNOUNCE_RACE        = 0x8c;
inline constexpr std::uint8_t MSG_ANNOUNCE_ATTRIB      = 0x8d;
inline constexpr std::uint8_t MSG_ANNOUNCE_CARD        = 0x8e;
inline constexpr std::uint8_t MSG_ANNOUNCE_NUMBER      = 0x8f;
inline constexpr std::uint8_t MSG_CARD_HINT            = 0xa0;
inline constexpr std::uint8_t MSG_TAG_SWAP             = 0xa1;
inline constexpr std::uint8_t MSG_RELOAD_FIELD         = 0xa2;
inline constexpr std::uint8_t MSG_AI_NAME              = 0xa3;
inline constexpr std::uint8_t MSG_SHOW_HINT            = 0xa4;
inline constexpr std::uint8_t MSG_PLAYER_HINT          = 0xa5;
inline constexpr std::uint8_t MSG_MATCH_KILL           = 0xaa;
inline constexpr std::uint8_t MSG_CUSTOM_MSG           = 0xb4;
inline constexpr std::uint8_t MSG_REMOVE_CARDS         = 0xbe;
inline constexpr std::uint8_t OLD_REPLAY_MODE          = 0xe7;

// --- card locations ---
inline constexpr std::uint32_t LOCATION_DECK            = 0x1;
inline constexpr std::uint32_t LOCATION_HAND            = 0x2;
inline constexpr std::uint32_t LOCATION_MZONE           = 0x4;
inline constexpr std::uint32_t LOCATION_SZONE           = 0x8;
inline constexpr std::uint32_t LOCATION_ONFIELD         = 0xc;
inline constexpr std::uint32_t LOCATION_GRAVE           = 0x10;
inline constexpr std::uint32_t LOCATION_REMOVED         = 0x20;
inline constexpr std::uint32_t LOCATION_EXTRA           = 0x40;
inline constexpr std::uint32_t LOCATION_OVERLAY         = 0x80;

// --- card positions ---
inline constexpr std::uint8_t POS_FACEUP_ATTACK        = 0x1;
inline constexpr std::uint8_t POS_FACEDOWN_ATTACK      = 0x2;
inline constexpr std::uint8_t POS_ATTACK               = 0x3;
inline constexpr std::uint8_t POS_FACEUP_DEFENSE       = 0x4;
inline constexpr std::uint8_t POS_FACEUP               = 0x5;
inline constexpr std::uint8_t POS_FACEDOWN_DEFENSE     = 0x8;
inline constexpr std::uint8_t POS_FACEDOWN             = 0xa;
inline constexpr std::uint8_t POS_DEFENSE              = 0xc;

// --- duel phases ---
inline constexpr std::uint32_t PHASE_DRAW               = 0x1;
inline constexpr std::uint32_t PHASE_STANDBY            = 0x2;
inline constexpr std::uint32_t PHASE_MAIN1              = 0x4;
inline constexpr std::uint32_t PHASE_BATTLE_START       = 0x8;
inline constexpr std::uint32_t PHASE_BATTLE_STEP        = 0x10;
inline constexpr std::uint32_t PHASE_DAMAGE             = 0x20;
inline constexpr std::uint32_t PHASE_DAMAGE_CAL         = 0x40;
inline constexpr std::uint32_t PHASE_BATTLE             = 0x80;
inline constexpr std::uint32_t PHASE_MAIN2              = 0x100;
inline constexpr std::uint32_t PHASE_END                = 0x200;

// --- event reasons ---
inline constexpr std::uint32_t REASON_DESTROY           = 0x1;
inline constexpr std::uint32_t REASON_RELEASE           = 0x2;
inline constexpr std::uint32_t REASON_TEMPORARY         = 0x4;
inline constexpr std::uint32_t REASON_MATERIAL          = 0x8;
inline constexpr std::uint32_t REASON_SUMMON            = 0x10;
inline constexpr std::uint32_t REASON_BATTLE            = 0x20;
inline constexpr std::uint32_t REASON_EFFECT            = 0x40;
inline constexpr std::uint32_t REASON_COST              = 0x80;
inline constexpr std::uint32_t REASON_ADJUST            = 0x100;
inline constexpr std::uint32_t REASON_LOST_TARGET       = 0x200;
inline constexpr std::uint32_t REASON_RULE              = 0x400;
inline constexpr std::uint32_t REASON_SPSUMMON          = 0x800;
inline constexpr std::uint32_t REASON_DISSUMMON         = 0x1000;
inline constexpr std::uint32_t REASON_FLIP              = 0x2000;
inline constexpr std::uint32_t REASON_DISCARD           = 0x4000;
inline constexpr std::uint32_t REASON_RDAMAGE           = 0x8000;
inline constexpr std::uint32_t REASON_RRECOVER          = 0x10000;
inline constexpr std::uint32_t REASON_RETURN            = 0x20000;
inline constexpr std::uint32_t REASON_FUSION            = 0x40000;
inline constexpr std::uint32_t REASON_SYNCHRO           = 0x80000;
inline constexpr std::uint32_t REASON_RITUAL            = 0x100000;
inline constexpr std::uint32_t REASON_XYZ               = 0x200000;
inline constexpr std::uint32_t REASON_REPLACE           = 0x1000000;
inline constexpr std::uint32_t REASON_DRAW              = 0x2000000;
inline constexpr std::uint32_t REASON_REDIRECT          = 0x4000000;
inline constexpr std::uint32_t REASON_LINK              = 0x10000000;

// --- player constants ---
inline constexpr std::uint8_t PLAYER_NONE              = 0x2;
inline constexpr std::uint8_t PLAYER_ALL               = 0x3;

// Canonical name for a duel message id, or an empty view when the id is
// not one upstream defines. Callers distinguish "unknown to the protocol"
// from "known but not decoded here" on the emptiness of this result.
constexpr std::string_view message_name(std::uint8_t id) noexcept {
	switch(id) {
	case 0x1: return "MSG_RETRY";
	case 0x2: return "MSG_HINT";
	case 0x3: return "MSG_WAITING";
	case 0x4: return "MSG_START";
	case 0x5: return "MSG_WIN";
	case 0x6: return "MSG_UPDATE_DATA";
	case 0x7: return "MSG_UPDATE_CARD";
	case 0x8: return "MSG_REQUEST_DECK";
	case 0xa: return "MSG_SELECT_BATTLECMD";
	case 0xb: return "MSG_SELECT_IDLECMD";
	case 0xc: return "MSG_SELECT_EFFECTYN";
	case 0xd: return "MSG_SELECT_YESNO";
	case 0xe: return "MSG_SELECT_OPTION";
	case 0xf: return "MSG_SELECT_CARD";
	case 0x10: return "MSG_SELECT_CHAIN";
	case 0x12: return "MSG_SELECT_PLACE";
	case 0x13: return "MSG_SELECT_POSITION";
	case 0x14: return "MSG_SELECT_TRIBUTE";
	case 0x15: return "MSG_SORT_CHAIN";
	case 0x16: return "MSG_SELECT_COUNTER";
	case 0x17: return "MSG_SELECT_SUM";
	case 0x18: return "MSG_SELECT_DISFIELD";
	case 0x19: return "MSG_SORT_CARD";
	case 0x1a: return "MSG_SELECT_UNSELECT_CARD";
	case 0x1e: return "MSG_CONFIRM_DECKTOP";
	case 0x1f: return "MSG_CONFIRM_CARDS";
	case 0x20: return "MSG_SHUFFLE_DECK";
	case 0x21: return "MSG_SHUFFLE_HAND";
	case 0x22: return "MSG_REFRESH_DECK";
	case 0x23: return "MSG_SWAP_GRAVE_DECK";
	case 0x24: return "MSG_SHUFFLE_SET_CARD";
	case 0x25: return "MSG_REVERSE_DECK";
	case 0x26: return "MSG_DECK_TOP";
	case 0x27: return "MSG_SHUFFLE_EXTRA";
	case 0x28: return "MSG_NEW_TURN";
	case 0x29: return "MSG_NEW_PHASE";
	case 0x2a: return "MSG_CONFIRM_EXTRATOP";
	case 0x32: return "MSG_MOVE";
	case 0x35: return "MSG_POS_CHANGE";
	case 0x36: return "MSG_SET";
	case 0x37: return "MSG_SWAP";
	case 0x38: return "MSG_FIELD_DISABLED";
	case 0x3c: return "MSG_SUMMONING";
	case 0x3d: return "MSG_SUMMONED";
	case 0x3e: return "MSG_SPSUMMONING";
	case 0x3f: return "MSG_SPSUMMONED";
	case 0x40: return "MSG_FLIPSUMMONING";
	case 0x41: return "MSG_FLIPSUMMONED";
	case 0x46: return "MSG_CHAINING";
	case 0x47: return "MSG_CHAINED";
	case 0x48: return "MSG_CHAIN_SOLVING";
	case 0x49: return "MSG_CHAIN_SOLVED";
	case 0x4a: return "MSG_CHAIN_END";
	case 0x4b: return "MSG_CHAIN_NEGATED";
	case 0x4c: return "MSG_CHAIN_DISABLED";
	case 0x50: return "MSG_CARD_SELECTED";
	case 0x51: return "MSG_RANDOM_SELECTED";
	case 0x53: return "MSG_BECOME_TARGET";
	case 0x5a: return "MSG_DRAW";
	case 0x5b: return "MSG_DAMAGE";
	case 0x5c: return "MSG_RECOVER";
	case 0x5d: return "MSG_EQUIP";
	case 0x5e: return "MSG_LPUPDATE";
	case 0x5f: return "MSG_UNEQUIP";
	case 0x60: return "MSG_CARD_TARGET";
	case 0x61: return "MSG_CANCEL_TARGET";
	case 0x64: return "MSG_PAY_LPCOST";
	case 0x65: return "MSG_ADD_COUNTER";
	case 0x66: return "MSG_REMOVE_COUNTER";
	case 0x6e: return "MSG_ATTACK";
	case 0x6f: return "MSG_BATTLE";
	case 0x70: return "MSG_ATTACK_DISABLED";
	case 0x71: return "MSG_DAMAGE_STEP_START";
	case 0x72: return "MSG_DAMAGE_STEP_END";
	case 0x78: return "MSG_MISSED_EFFECT";
	case 0x79: return "MSG_BE_CHAIN_TARGET";
	case 0x7a: return "MSG_CREATE_RELATION";
	case 0x7b: return "MSG_RELEASE_RELATION";
	case 0x82: return "MSG_TOSS_COIN";
	case 0x83: return "MSG_TOSS_DICE";
	case 0x84: return "MSG_ROCK_PAPER_SCISSORS";
	case 0x85: return "MSG_HAND_RES";
	case 0x8c: return "MSG_ANNOUNCE_RACE";
	case 0x8d: return "MSG_ANNOUNCE_ATTRIB";
	case 0x8e: return "MSG_ANNOUNCE_CARD";
	case 0x8f: return "MSG_ANNOUNCE_NUMBER";
	case 0xa0: return "MSG_CARD_HINT";
	case 0xa1: return "MSG_TAG_SWAP";
	case 0xa2: return "MSG_RELOAD_FIELD";
	case 0xa3: return "MSG_AI_NAME";
	case 0xa4: return "MSG_SHOW_HINT";
	case 0xa5: return "MSG_PLAYER_HINT";
	case 0xaa: return "MSG_MATCH_KILL";
	case 0xb4: return "MSG_CUSTOM_MSG";
	case 0xbe: return "MSG_REMOVE_CARDS";
	case 0xe7: return "OLD_REPLAY_MODE";
	default: return {};
	}
}

constexpr bool is_known_message(std::uint8_t id) noexcept {
	return !message_name(id).empty();
}

} // namespace edopro_next::client::protocol

#endif // EDOPRO_NEXT_CLIENT_PROTOCOL_CONSTANTS_H
