#!/usr/bin/env python3
"""Generate the duel-message id table from upstream headers.

The table is *derived*, never hand-maintained, so it cannot silently drift from
the engine's own constants. CI re-runs this and fails if the checked-in file
differs.

Sources (both upstream-owned, never edited by us):
  gframe/ocgapi_constants.h  -- MSG_* as defined by ocgcore
  gframe/common.h            -- client-side pseudo-messages (e.g. OLD_REPLAY_MODE)

Usage:
    python tools/generate_messages.py            # write the table
    python tools/generate_messages.py --check    # verify it is up to date
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "tools" / "replaytrace" / "messages.py"

# (path, regex, note) - only names we actually want in the table.
SOURCES = [
    (REPO / "gframe" / "ocgapi_constants.h", re.compile(r"^#define\s+(MSG_[A-Z0-9_]+)\s+(\d+)"), "ocgcore"),
    (REPO / "gframe" / "common.h", re.compile(r"^#define\s+(OLD_REPLAY_MODE)\s+(\d+)"), "client"),
]

HEADER = '''"""Duel message id -> name.

GENERATED by tools/generate_messages.py from upstream headers. Do not edit.
Re-generate with:  python tools/generate_messages.py
"""

# fmt: off
MESSAGES = {
'''

FOOTER = """}
# fmt: on


def name_for(msg_id: int) -> str:
    \"\"\"Return the canonical name, or a stable placeholder for unknown ids.

    Unknown ids must still produce deterministic output, so traces of replays
    containing messages this table does not know remain diffable.
    \"\"\"
    return MESSAGES.get(msg_id, f"UNKNOWN_{msg_id}")
"""


def collect() -> dict[int, str]:
    table: dict[int, str] = {}
    for path, pattern, origin in SOURCES:
        if not path.exists():
            sys.exit(f"missing upstream header: {path}")
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            m = pattern.match(line.strip())
            if not m:
                continue
            name, value = m.group(1), int(m.group(2))
            if value in table and table[value] != name:
                # Genuine collision would make traces ambiguous; refuse rather
                # than silently pick one.
                sys.exit(f"id {value} maps to both {table[value]} and {name} ({origin})")
            table[value] = name
    return table


def render(table: dict[int, str]) -> str:
    lines = [f"    {mid}: {name!r}," for mid, name in sorted(table.items())]
    return HEADER + "\n".join(lines) + "\n" + FOOTER


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify without writing")
    args = ap.parse_args()

    table = collect()
    text = render(table)

    if args.check:
        if not OUT.exists():
            print(f"{OUT} does not exist; run without --check", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT} is stale; re-run: python tools/generate_messages.py", file=sys.stderr)
            return 1
        print(f"message table up to date ({len(table)} ids)")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(REPO)} ({len(table)} ids)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
